# Generated by Django 4.2.10 on 2024-02-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_created_alter_proyecto_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(upload_to='proyectos/images'),
        ),
    ]
