# Generated by Django 4.2.10 on 2024-02-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(upload_to='proyectos/images', verbose_name='Imagenes'),
        ),
    ]
